#!/bin/bash

while read oldrev newrev refname; do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" == "$branch" ]; then
        echo "Publishing..."
        make clean && make publish && ghp-import output && git push https://github.com/tchamberlin/tchamberlin.github.io gh-pages:master
        echo "...complete!"
    fi
done
